yatube/core/urls.py
from django.urls import path
from django.conf import settings

from . import views

app_name = 'core'

urlpatterns = [
]

if settings.DEBUG:
    urlpatterns = [
        path('404/', views.page_not_found, name='404'),
        path('403/', views.csrf_failure, name='403'),
        path('500', views.error_code_500, name='500')
    ] + urlpatterns

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_posts'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/comment/',
         views.add_comment, name='add_comment'),
    path('follow/', views.follow_index, name='follow_index'),
    path('profile/<str:username>/follow/',
         views.profile_follow, name='profile_follow'),
    path('profile/<str:username>/unfollow/',
         views.profile_unfollow, name='profile_unfollow'),
]

yatube/users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path("about/", include('about.urls', namespace='about')),
    path('error/', include('core.urls', namespace='core')),
    path('', include('posts.urls', namespace='posts')),
]
handler404 = 'core.views.page_not_found'
handler403 = 'core.views.csrf_failure'
handler500 = 'core.views.error_code_500'


if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/templates/includes/footer.html
{% load static %}

<footer class="border-top text-center py-3">
    <!-- тег span используется для добавления нужных стилей отдельным участкам текста --> 
    <p>© {{ year }} Copyright <span style="color:red">Ya</span>tube</p>    
  </footer>

yatube/templates/includes/header.html
{% load static %} {% with request.resolver_match.view_name as view_name %}
<header>
  <nav class="navbar navbar-light" style="background-color: lightskyblue">
    <div class="container">
      <a class="navbar-brand" href="{% url 'posts:index' %}">
        <img
          src="{% static 'img/logo.png' %}"
          width="30"
          height="30"
          class="d-inline-block align-top"
          alt=""
        />
        <span style="color: red">Ya</span>tube
      </a>
      {# Добавлено в спринте #} {% comment %} Меню - список пунктов со
      стандартными классами Bootsrap. Класс nav-pills нужен для выделения
      активных пунктов {% endcomment %}
      <ul class="nav nav-pills">
        <li class="nav-item">
          <a
            class="nav-link {% if view_name == 'about:author' %}active{% endif %}"
            href="{% url 'about:author' %}"
            >Об авторе</a
          >
        </li>
        <li class="nav-item">
          <a
            class="nav-link {% if view_name == 'about:tech' %}active{% endif %}"
            href="{% url 'about:tech' %}"
            >Технологии</a
          >
        </li>
        {% if request.user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'posts:post_create' %}"
            >Новая запись</a
          >
        </li>
        <li class="nav-item">
          <a class="nav-link link-light" href="<!--  -->">Изменить пароль</a>
        </li>
        <li class="nav-item">
          <span class="nav-link link-light">
            Пользователь:
            <a href="{% url 'posts:profile' user.username%}"
              >{{ user.username }}</a
            ></span
          >
        </li>
        <li class="nav-item">
          <a class="nav-link link-light" href="{% url 'users:logout' %}">Выйти</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link link-light" href="{% url 'users:login' %}">Войти</a>
        </li>
        <li class="nav-item">
          <a class="nav-link link-light" href="<!--  -->">Регистрация</a>
        </li>
        {% endif %}
      </ul>
      {# Конец добавленого в спринте #}
    </div>
  </nav>
</header>
{% endwith %}