yatube/core/urls.py
from django.urls import path
from django.conf import settings

from . import views

app_name = 'core'

urlpatterns = [
]

if settings.DEBUG:
    urlpatterns = [
        path('404/', views.page_not_found, name='404'),
        path('403/', views.csrf_failure, name='403'),
        path('500', views.error_code_500, name='500')
    ] + urlpatterns

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_posts'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/comment/',
         views.add_comment, name='add_comment'),
    path('follow/', views.follow_index, name='follow_index'),
    path('profile/<str:username>/follow/',
         views.profile_follow, name='profile_follow'),
    path('profile/<str:username>/unfollow/',
         views.profile_unfollow, name='profile_unfollow'),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path("about/", include('about.urls', namespace='about')),
    path('error/', include('core.urls', namespace='core')),
    path('', include('posts.urls', namespace='posts')),
]
handler404 = 'core.views.page_not_found'
handler403 = 'core.views.csrf_failure'
handler500 = 'core.views.error_code_500'


if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()
OUTPUT_DATA_POST = 'Text: {}, Group: {}, Author: {}'
OUTPUT_DATA_FOLLOW = '{} -> {}'


class Group(models.Model):
    title = models.CharField(max_length=200, verbose_name='Заголовок')
    slug = models.SlugField(max_length=200, unique=True,
                            verbose_name='ID группы')
    description = models.TextField(verbose_name='Описание')

    class Meta:
        verbose_name = 'Группа'
        verbose_name_plural = 'Группы'

    def __str__(self):
        return self.title


class Post(models.Model):

    text = models.TextField(
        verbose_name='Текст',
        help_text='Введите текст поста'
    )
    pub_date = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата публикации'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор'
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts',
        verbose_name='Группа',
        help_text='Группа, к которой будет относиться пост'
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    class Meta:
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'
        ordering = ('-pub_date',)

    def __str__(self):
        return OUTPUT_DATA_POST.format(
            self.text[:15],
            self.group,
            self.author.username
        )


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Пост',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор',
    )
    text = models.TextField(
        verbose_name='Текст коммента',
        help_text='Введите текст коммента'
    )
    created = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата публикации коммента'
    )

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

    def __str__(self):
        return self.text[:20]


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
        verbose_name='Подписчик'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
        verbose_name='Автор'
    )

    class Meta:
        verbose_name = 'Подписка'
        verbose_name_plural = 'Подписки'
        constraints = [models.UniqueConstraint(fields=['user', 'author'],
                                               name='unique_follow')]

    def __str__(self):
        return OUTPUT_DATA_FOLLOW.format(
            self.user.username,
            self.author.username)

yatube/posts/forms.py
from django import forms

from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, render, redirect
from django.views.decorators.cache import cache_page

from .forms import PostForm, CommentForm
from .models import Group, Post, User, Follow

POSTS_PER_PAGE = 10


def pager(request, post_list):
    return Paginator(post_list, POSTS_PER_PAGE).get_page(
        request.GET.get('page'))


@cache_page(20)
def index(request):
    return render(request, 'posts/index.html', {
        'page_obj': pager(request, Post.objects.all())
    })


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    return render(request, 'posts/group_list.html', {
        'group': group,
        'page_obj': pager(request, group.posts.all())
    })


def profile(request, username):
    author = get_object_or_404(User, username=username)
    return render(request, 'posts/profile.html', {
        'page_obj': pager(request, author.posts.all()),
        'author': author,
        'following':
            request.user.is_authenticated
            and request.user != author
            and author.following.filter(user=request.user).exists()})


def post_detail(request, post_id):
    return render(request, 'posts/post_detail.html', {
        'post': get_object_or_404(Post, id=post_id),
        'form': CommentForm(request.POST or None)
    })


@login_required
def post_create(request):
    form = PostForm(request.POST or None,
                    files=request.FILES or None)
    if not form.is_valid():
        return render(request, 'posts/post_create.html', {'form': form})
    post = form.save(commit=False)
    post.author = request.user
    post.save()
    return redirect('posts:profile', request.user.username)


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if post.author != request.user:
        return redirect('posts:post_detail', post_id)
    form = PostForm(request.POST or None, instance=post,
                    files=request.FILES or None)
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post.pk)
    return render(request, 'posts/post_create.html',
                  {'is_edit': True, 'form': form})


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    return render(request, 'posts/follow.html', {
        'page_obj': pager(request, Post.objects.filter(
            author__following__user=request.user))})


@login_required
def profile_follow(request, username):
    follower = request.user
    following = get_object_or_404(User, username=username)
    if follower != following:
        if not Follow.objects.filter(user=follower, author=following).exists():
            Follow.objects.create(user=follower, author=following)
    return redirect('posts:profile', username=username)


@login_required
def profile_unfollow(request, username):
    get_object_or_404(
        Follow,
        user=request.user,
        author__username=username
    ).delete()
    return redirect('posts:profile', username=username)

yatube/templates/posts/follow.html
{% extends 'base.html' %}

{% block title %}Последние обновления на сайте{% endblock %}
{% block content %}
  {% include 'posts/includes/switcher.html' with follow=True %}
  {% for post in page_obj %}
    {% include 'posts/includes/show_post.html' %}
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}

{% block title %}
  {{ group.title }}
{% endblock %}

{% block content %}
  <h1> {{ group.title}} </h1>
  <p>{{group.description|linebreaks }}</p>
  {% include 'posts/includes/paginator.html' %}
  {% for post in page_obj %}
    {% include 'posts/includes/show_post.html' %}
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}

  {% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% load cache %}

{% cache 600 index_page %}
{% block title %}
  Главная страница проекта Yatube
{% endblock %}

{% block content %}
  {% include 'posts/includes/switcher.html' with index=True %}
  <h1>Последние обновления.</h1>
  {% for post in page_obj %}
    {% include 'posts/includes/show_post.html' %}
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
{% endblock %}
{% endcache %} 

yatube/templates/posts/post_create.html
{% extends "base.html" %}

{% block title %}
  {% if is_edit %} Изменить пост {% else %} Новый пост {% endif %} 
{% endblock %}

{% block content %}
  {% load user_filters %}
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">       
            {% if is_edit %}Изменить пост{% else %}Новый пост{% endif %}              
          </div>
          <div class="card-body">        
            <form action="" method="post" enctype="multipart/form-data">
              {% csrf_token %}     
              {{ form.non_field.errors }}
              {% for item in form %}
                <div class="form-group row my-3 p-3">
                  <label for="{{ item.id_for_label}}">
                    {{ item.label }}
                    <span class="required text-danger" >*</span>                  
                  </label>
                  {{item|addclass:"form-control"}}
                  <div class="invalid-feedback">
                    {{item.errors}}
                  </div>
                  <small id="id_text-help" class="form-text text-muted">
                    {{ item.help_text }}
                  </small>                  
                </div>       
              {% endfor %}
  
              <div class="d-flex justify-content-end">
                <button type="submit" class="btn btn-primary">
                  {% if is_edit %}Сохранить{% else %}Добавить{% endif %}  
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load thumbnail %}

{% block title %}
  Пост: {{ post.text|truncatechars:30}}
{% endblock %}

{% block content %}
  <main>
    <div class="row">
      <aside class="col-12 col-md-3">
        <ul class="list-group list-group-flush">
          <li class="list-group-item">
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
          {% if post.group %}
            <li class="list-group-item">
              Группа: 
              <a href="{% url 'posts:group_posts' post.group.slug %}">#{{ post.group.title }}</a>
            </li>
          {% endif %}
          
          <li class="list-group-item">
            Автор: 
            <a href="{% url 'posts:profile' post.author.username %}"> {{post.author.username}} </a>
          </li>
          <li class="list-group-item">
            Всего постов автора: {{ post.author.posts.count }}
          </li>
        </ul>
      </aside>
    <article class="col-12 col-md-9">
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
            <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">
      {% endthumbnail %} 
      <p>
        {{post.text|linebreaks}}
      </p>
      {% if post.author == user %}
        <a class="btn btn-primary" href="{% url 'posts:post_edit' post.pk %}">
          Редактировать запись
        </a> 
      {% endif%}
      {% include 'posts/includes/commentaries.html' %}
    </article>
   </div>
 </main>

{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}

{% block title %}
  Профайл пользователя {{ author.get_full_name }}
{% endblock %}

{% block content %}
  <h1>Все посты пользователя {{ author.get_full_name }} </h1>
  <h3>Всего постов: {{ author.posts.count}} </h3> 
  <h3>Всего подписок: {{ author.follower.count}} </h3> 
  <h3>Всего подпичиков: {{ author.following.count}} </h3>
  <h3>Всего комментарев: {{ author.comments.count }} </h3> 

  {% if user != author and user.is_authenticated %}
    {% if following %}
      <a class="btn btn-lg btn-light"
      href="{% url 'posts:profile_unfollow' author.username %}"
      role="button">Отписаться</a>
    {% else %}
        <a class="btn btn-lg btn-primary"
        href="{% url 'posts:profile_follow' author.username %}"
        role="button">Подписаться</a>
    {% endif %}
  {% endif %}

  {% for post in page_obj %}
    {% include 'posts/includes/show_post.html' %}
  {% endfor %}
  {% include 'posts/includes/paginator.html' %} 
    
{% endblock %}